### ISSUE TITLE
Native Ads

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/carbo#1]
Currently there is no way to CRUD Ads through our system — all ads are scraped from 3rd-party sources.

As a User I want to create/update/delete my own Ads. Those ads should be displayed in the same way as as currently existed 3rd-party ads.

Steps we have to implement:

- [x] ~~Ad model should not be dependent on `ads_source_id`~~
- [x] Ad model ~~should not be dependent on `address` or it can have~~ auto generated internal address if necessary
- [x] Ad model should be associated with User model
- [x] Effective Ads should not be affected by this change
- [x] PutAd should not be affected by this change and 3rd-party providers should work in the same way they work right now
- [x] ~~`deleted` should be changed to `deleted_at` and maybe used with `acts_as_paranoid` gem~~
- [x] AdCarContract should only be mandatory for Ads providers working with Cars
- [x] Native Ad should have images stored in our system but 3rd-party Ads should preserve existing behavior
- [x] Native Ads should have user generated AdOptions associated (maybe moderated)
- [x] Migrate existing Ads to new structure (if necessary)
- [x] Adjust Budget Widget to new structure
- [x] Providers should avoid updating (actualizing) ads which have been edited Natively
