### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/carbo#12]
Basic achievements should be implemented. There can be 2 types of achievements: `unique` for example, being 1000th User signed up and `repeatable`, say for visiting 1000 ads in a single day.

# Achievement types

* Referrer
* Sign Up (unique)
* Favorites
* Visited Ads
* Sign In
* Message Posted
* Installed new build among the first
* Chats
  * Other Ad
  * My Ad
  * Created
  * Did Invite
  * Was Invited

# TODO

- [ ] Create Achievements model (`photo`, `translations [title, description]`, `type [unique, repeatable]`)
- [ ] Create pre-defined Achievement records 
- [ ] Create UserAchievements model (`achievement_id`, `progress`, `finished_times`)
- [ ] Enforce creation of UserAchievements according to new Events happening in the system
- [ ] Create UserAchievements for past Events already in the system
- [ ] Consider creating unique Achievements not based on Events 
- [ ] View UserAchievements
- [ ] Consider allowing Users to hide their Achievements
- [ ] Link to User Achievement(s)
- [ ] Scoreboard
