### ISSUE TITLE
Stories

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/carbo#14]
The most basic implementation of Stories is required for now.

- [ ] CRUD
- [ ] Stories connection path
- [ ] Comment on story goes to the chat of a new type that is based on a story, not on Ad
- [ ] This new type of chat should be allowed to add mutual friends
- [ ] Story should be shareable with any of your friends (consider what to do with connection path in this case)
- [ ] Statistics gathered for Stories (views, comments, shares)
- [x] ~~No content composer required~~
- [x] ~~No archive required~~
