### ISSUE TITLE
Smart Filters

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/carbo#15]
# Data types
- [ ] string
- [ ] text
- [ ] number
- [ ] float
- [ ] range-defined
- [ ] range-arbitrary
- [ ] boolean
- [ ] array-multiple
- [ ] array-single

# Validations
- [ ] Text pattern
- [ ] Text min/max length
- [ ] Number min/max value
- [ ] Required true/false

# Dependent filters (?)
For example, Maker->Model dependency. Requirements TBD

# Configurable nulls
Consider, there is and Ad with Ad Option `color=green`. And User wants to search for all Ads with `color=green`. The question is, should User see Ads with `color=null` ? Consider, making it configurable by User with default to `No, User should not see color=null Ads`

# Ensure AdOptions work accordingly on Ad creation

# Sorting
Filters positions should be configurable from backend
