### ISSUE TITLE
Worldwide support

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/carbo#2]
Currently it is assumed that application will only be used in Ukraine. But we have to expand User base.

- [ ] Send SMS to any country
- [x] Texts should be translated and localized to English and Ukrainian
- [ ] Guess country code for contact with a phone in local format according to owner phone number country code and majority of other contacts country codes. Consider adding manual setting "Guess country codes as..." and also consider making UserContacts editable in this case.
- [ ] Allow multiple languages in Ad description to be added manually
- [ ] International countries and cities list
