### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by viktorvsk** [viktorvsk/carbo#22]
# Global Settings Who Can See

* Everybody
* Nobody
* My contacts
* Network of my contacts (?)

# Subjects to Control

- [ ] Who can see me as registered in contacts
- [ ] Who can see my ads
- [ ] Who can see my profile
- [ ] Who can see my phone number on profile screen
- [ ] Who can see my online (TBD)
- [ ] Who can see my profile photo
- [ ] Who can answer my stories
- [ ] Who can share my stories
- [ ] Who can invite me to chat (includes Ask)
